### PR TITLE
v.io/x/lib/vlog: allow for configuration via a function call

### PR DESCRIPTION
**Pull request by cosnicolaou**
Allow for configuration via a function call rather than just via flags.

### CODE REVIEW

**Comment by razvanm** [comment]
Hm... did you really want this as merge in the master branch? I typically do the squash to avoid having a messy history.

**Comment by cosnicolaou** [comment]
you're right, I get confused by the github workflow...

Cheers, Cos.

**Comment by razvanm** [comment]
Quick note: I changed the GitHub settings for this repo to only allow squash merging.

merge

**Comment by cosnicolaou** [comment]
I made the same change to the core repo. I'll go ahead and merge the
factories change now.

Cheers, Cos.


On Sat, May 5, 2018 at 5:36 PM, Razvan Musaloiu-E. <notifications@github.com

**Pull request merged**
